if __name__ == '__main__':
    print("=" * 60)
    print("ENHANCED SAFETY DASHBOARD")
    print("=" * 60)
    print("Features:")
    print("  • User Authentication & Registration")
    print("  • Real Incident Reporting Forms")
    print("  • Edit/Delete Incident Reports")
    print("  • Admin Status Management (Pending/Open/Solved)")
    print("  • Email Notifications (requires configuration)")
    print("  • Interactive Dashboard with Charts")
    print("  • CSV & HTML Export")
    print("  • Database Storage (SQLite)")
    print("  • Role-based Access Control")
    print("")
    print("Default Admin Credentials:")
    print("  Username: admin")
    print("  Password: admin123")
    print("")
    print("IMPORTANT: Configure email settings in app.py for notifications")
    print("")
    print("Network Access:")
    print("  Local:    http://localhost:8000")
    print("  Network:  http://192.168.50.118:8000")
    print("")
    print("Press CTRL+C to stop the server")
    print("=" * 60)

    app.run(debug=True, port=8000, host='0.0.0.0')